### ISSUE TITLE
Time config input validation

### ISSUE THREAD

**Issue by thakurtushar02** [SoftEng701-Group5/assignment1#157]
Only allow numbers, no other characters

**Comment by raymondhonsumchiu** [comment]
New bug with the implemented validation:
Having an incorrect input in the minutes or seconds field will result in the invalid input warning being displayed, however if a valid input was placed in the corresponding seconds/minutes field after the incorrect input, the warning disappears despite the total time being incorrect. (This bug does not affect the disabling of the start button when there's an incorrect input, just the visual warning)
