### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by dongmeilim** [SoftEng701-Group5/assignment1#24]
Using Firebase:

- Create Firebase project
  - Email: se701group5.uoa@gmail.com
  - Password: Goodgradesplease9
- Allow user authentication with Firebase project
  - Create user login/sign-out functionality
  - Create user Sign-up functionality
  - Create “service” file for easy access to Firebase authentication functionality

**Comment by YungiKim1999** [comment]
This was completed in the feature-firebase-CRUD pull request
