### ISSUE TITLE
Task Board columns

### ISSUE THREAD

**Issue by IngemarWatt** [SoftEng701-Group5/assignment1#31]
Add 3 vertical columns to the screen. The columns are to contain tasks. The leftmost task should have a dummy '+' button that will have its functionality linked up later on. The 'Today's Tasks' screen has a similar list that Yuno mentioned could be heavily reused. in our screen

**Comment by max-gurr** [comment]
Could you break this up into some smaller tasks? Ideally, the issues can be used for individual group members to pick up pieces of work
